#!/bin/bash

DIR=`realpath "$0"`
[ -f "$DIR/$1.port" ] && PORT=`cat "$DIR/$1.port"` || PORT="22"
[ -f "$DIR/$1.user" ] && USER=`cat "$DIR/$1.user"` || USER="root"
[ -f "$DIR/$1.host" ] && HOST=`cat "$DIR/$1.host"` || HOST="$1"

if [ -f "$DIR/$1.pk" ]
then
    /usr/bin/ssh -i "$DIR/$1.pk" -p "$PORT" -l "$USER" "$HOST" true && /usr/bin/date +%s > "$DIR/$1.timestamp"
else
    /usr/bin/ssh -p "$PORT" -l "$USER" "$HOST" true && /usr/bin/date +%s > "$DIR/$1.timestamp"
fi
